import { useState } from "react";
import { motion } from "framer-motion";
import { Calendar, Copy, Check, Sparkles, RefreshCw, Clock } from "lucide-react";
import { Button } from "@/components/ui/button";
import Header from "@/components/Header";
import { toast } from "sonner";

interface ScheduleItem {
  time: string;
  subject: string;
  topic: string;
  duration: string;
  color: string;
}

const daysOfWeek = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

const mockSchedule: Record<string, ScheduleItem[]> = {
  Monday: [
    { time: "4:00 PM", subject: "Math", topic: "Fractions Practice", duration: "25 min", color: "bg-kidzie-coral" },
    { time: "4:30 PM", subject: "Science", topic: "How Plants Grow", duration: "20 min", color: "bg-kidzie-green" },
    { time: "5:00 PM", subject: "Reading", topic: "Story Time", duration: "15 min", color: "bg-kidzie-purple" },
  ],
  Tuesday: [
    { time: "4:00 PM", subject: "History", topic: "Ancient Egypt", duration: "20 min", color: "bg-kidzie-yellow" },
    { time: "4:30 PM", subject: "Math", topic: "Decimals & Money", duration: "25 min", color: "bg-kidzie-coral" },
    { time: "5:00 PM", subject: "Art", topic: "Color Theory Fun", duration: "20 min", color: "bg-kidzie-pink" },
  ],
  Wednesday: [
    { time: "4:00 PM", subject: "Science", topic: "Solar System", duration: "25 min", color: "bg-kidzie-blue" },
    { time: "4:30 PM", subject: "English", topic: "Vocabulary Games", duration: "15 min", color: "bg-kidzie-teal" },
    { time: "5:00 PM", subject: "Math", topic: "Word Problems", duration: "20 min", color: "bg-kidzie-coral" },
  ],
  Thursday: [
    { time: "4:00 PM", subject: "Geography", topic: "Continents & Oceans", duration: "20 min", color: "bg-kidzie-green" },
    { time: "4:30 PM", subject: "Science", topic: "Animals & Habitats", duration: "25 min", color: "bg-kidzie-teal" },
    { time: "5:00 PM", subject: "Reading", topic: "Comic Book Creating", duration: "20 min", color: "bg-kidzie-purple" },
  ],
  Friday: [
    { time: "4:00 PM", subject: "Math", topic: "Geometry Shapes", duration: "20 min", color: "bg-kidzie-coral" },
    { time: "4:30 PM", subject: "Music", topic: "Rhythm Patterns", duration: "15 min", color: "bg-kidzie-pink" },
    { time: "5:00 PM", subject: "Free Explore", topic: "Ask KidZie Anything!", duration: "30 min", color: "bg-kidzie-yellow" },
  ],
  Saturday: [
    { time: "10:00 AM", subject: "Science", topic: "Fun Experiments", duration: "30 min", color: "bg-kidzie-green" },
    { time: "10:45 AM", subject: "Art", topic: "Drawing Challenge", duration: "25 min", color: "bg-kidzie-pink" },
  ],
  Sunday: [
    { time: "11:00 AM", subject: "Review", topic: "Weekly Review Game", duration: "20 min", color: "bg-kidzie-blue" },
    { time: "11:30 AM", subject: "Free Explore", topic: "Curiosity Time!", duration: "30 min", color: "bg-kidzie-yellow" },
  ],
};

const ScheduleGenerator = () => {
  const [selectedDay, setSelectedDay] = useState("Monday");
  const [copied, setCopied] = useState(false);

  const handleCopyToCalendar = () => {
    const schedule = mockSchedule[selectedDay];
    const calendarText = schedule
      .map((item) => `${item.time} - ${item.subject}: ${item.topic} (${item.duration})`)
      .join("\n");

    const fullText = `📚 KidZie Study Schedule - ${selectedDay}\n\n${calendarText}\n\n🌟 Generated by KidZie AI`;

    navigator.clipboard.writeText(fullText);
    setCopied(true);
    toast.success("Schedule copied! Paste it into Google Calendar 📋");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyGoogleCalendarLink = () => {
    const schedule = mockSchedule[selectedDay];
    // Create a Google Calendar event URL for the first item as example
    const item = schedule[0];
    const title = encodeURIComponent(`${item.subject}: ${item.topic}`);
    const details = encodeURIComponent(`KidZie AI Study Session\n\nTopic: ${item.topic}\nDuration: ${item.duration}`);
    const url = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${details}`;

    window.open(url, "_blank");
    toast.success("Opening Google Calendar! 📅");
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <h1 className="text-3xl font-display font-bold">
            Study <span className="text-gradient-hero">Schedule</span> 📅
          </h1>
          <p className="text-muted-foreground mt-1">
            AI-generated study plan based on your child's learning needs
          </p>
        </motion.div>

        {/* Day selector */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="flex overflow-x-auto gap-2 mb-8 pb-2"
        >
          {daysOfWeek.map((day) => (
            <button
              key={day}
              onClick={() => setSelectedDay(day)}
              className={`px-4 py-2.5 rounded-full text-sm font-bold whitespace-nowrap transition-all duration-200 ${
                selectedDay === day
                  ? "gradient-hero text-primary-foreground shadow-glow-teal"
                  : "bg-card text-muted-foreground hover:bg-muted shadow-soft"
              }`}
            >
              {day}
            </button>
          ))}
        </motion.div>

        {/* Schedule items */}
        <div className="space-y-4 mb-8">
          {mockSchedule[selectedDay].map((item, i) => (
            <motion.div
              key={`${selectedDay}-${i}`}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.15 + i * 0.08 }}
              className="bg-card rounded-2xl p-5 shadow-card flex items-center gap-4 hover:shadow-elevated transition-shadow"
            >
              {/* Time */}
              <div className="text-center min-w-[70px]">
                <p className="text-sm font-bold text-foreground">{item.time}</p>
                <p className="text-xs text-muted-foreground flex items-center gap-1 justify-center mt-1">
                  <Clock className="w-3 h-3" />
                  {item.duration}
                </p>
              </div>

              {/* Divider */}
              <div className={`w-1 h-12 rounded-full ${item.color}`} />

              {/* Content */}
              <div className="flex-1">
                <p className="font-bold text-sm">{item.subject}</p>
                <p className="text-sm text-muted-foreground">{item.topic}</p>
              </div>

              {/* Subject badge */}
              <div className={`${item.color} text-primary-foreground px-3 py-1 rounded-full text-xs font-bold`}>
                {item.subject}
              </div>
            </motion.div>
          ))}
        </div>

        {/* Actions */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
          className="flex flex-wrap gap-3"
        >
          <Button
            onClick={handleCopyToCalendar}
            className="gradient-hero text-primary-foreground rounded-full font-bold shadow-glow-teal px-6"
          >
            {copied ? <Check className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
            {copied ? "Copied!" : "Copy Schedule"}
          </Button>

          <Button
            onClick={handleCopyGoogleCalendarLink}
            variant="outline"
            className="rounded-full font-bold px-6"
          >
            <Calendar className="w-4 h-4 mr-2" />
            Add to Google Calendar
          </Button>

          <Button
            variant="outline"
            className="rounded-full font-bold px-6"
            onClick={() => toast.info("Schedule regeneration will use AI when backend is connected! 🤖")}
          >
            <RefreshCw className="w-4 h-4 mr-2" />
            Regenerate
          </Button>
        </motion.div>

        {/* Info card */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
          className="mt-8 bg-kidzie-teal/5 border border-kidzie-teal/20 rounded-2xl p-5"
        >
          <div className="flex items-start gap-3">
            <Sparkles className="w-5 h-5 text-kidzie-teal flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-bold text-foreground">How it works</p>
              <p className="text-sm text-muted-foreground mt-1">
                KidZie AI analyzes your child's learning patterns, weak points, and interests to create 
                a personalized study schedule. Sessions are kept short (15-30 min) to match children's 
                attention spans. Once connected to the backend, schedules will update automatically!
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default ScheduleGenerator;
